// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      print("WEB");
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Your web app's Firebase configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtWIFNJDatVKzhra2kCBNj-NzJ1_5zn5k',
    appId: '1:500852408753:web:047da0af98c902739bbd90',
    messagingSenderId: '500852408753',
    projectId: 'tictactwo-c1026',
    authDomain: 'tictactwo-c1026.firebaseapp.com',
    storageBucket: 'tictactwo-c1026.firebasestorage.app',
    measurementId: 'G-KVK9X1K6NW',
  );

  // For Firebase JS SDK v7.20.0 and later, measurementId is optional

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNtUokof-dJjFp7cnbMyTLw3sVIsZu2OE',
    appId: '1:500852408753:android:a5d6731c32558dd99bbd90',
    messagingSenderId: '500852408753',
    projectId: 'tictactwo-c1026',
    storageBucket: 'tictactwo-c1026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGE0P0oON1BiyEfyvQCHVIu6yAN9muzp4',
    appId: '1:500852408753:ios:2e72f33052129f659bbd90',
    messagingSenderId: '500852408753',
    projectId: 'tictactwo-c1026',
    storageBucket: 'tictactwo-c1026.firebasestorage.app',
    iosBundleId: 'com.example.ticTacTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGE0P0oON1BiyEfyvQCHVIu6yAN9muzp4',
    appId: '1:500852408753:ios:2e72f33052129f659bbd90',
    messagingSenderId: '500852408753',
    projectId: 'tictactwo-c1026',
    storageBucket: 'tictactwo-c1026.firebasestorage.app',
    iosBundleId: 'com.example.ticTacTwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtWIFNJDatVKzhra2kCBNj-NzJ1_5zn5k',
    appId: '1:500852408753:web:0120655024d901cf9bbd90',
    messagingSenderId: '500852408753',
    projectId: 'tictactwo-c1026',
    authDomain: 'tictactwo-c1026.firebaseapp.com',
    storageBucket: 'tictactwo-c1026.firebasestorage.app',
    measurementId: 'G-7QK5DPGRZN',
  );

}